apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: question-service
  type: ClusterIP
status:
  loadBalancer: {}
