version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./local/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: peerPrepDB
    networks:
      - app_network

  question-service:
    build:
      context: ./backend/src/question-service
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src/question-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/peerPrepDB?authSource=admin
      - PORT=4000
    depends_on:
      - mongo
    networks:
      - app_network

  user-service:
    build:
      context: ./backend/src/user-service
    ports:
      - "4001:4001"
    volumes:
      - ./backend/src/user-service:/app
      - /app/node_modules
    environment:
      - DB_LOCAL_URI=mongodb://root:example@mongo:27017/peerPrepDB?authSource=admin
      - PORT=4001
    depends_on:
      - mongo
    networks:
      - app_network

  collab-service:
    build:
      context: ./backend/src/collab-service
    ports:
      - "4002:4002"
    volumes:
      - ./backend/src/collab-service:/app
      - /app/node_modules
    environment:
      - DB_LOCAL_URI=mongodb://root:example@mongo:27017/peerPrepDB?authSource=admin
      - PORT=4002
    depends_on:
      - mongo
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: peerprep_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - question-service
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
